### ISSUE TITLE
Support for Thunderbird 68

### ISSUE THREAD

**Issue by dillenger** [mjg/QuoteCollapse#13]
I transformed QuoteCollapse 1.1.1 to a legacy webextension version.
Thunderbird 68+ only, includes a toolbarbutton and a keybinding [q].

[quotecollapse-2.0-tb.zip](https://github.com/mjg/QuoteCollapse/files/3348220/quotecollapse-2.0-tb.zip)

**Comment by mjg** [comment]
Thanks for your efforts and for the ping!
For another extension of mine, I had tried the conversion to a webextension (for Firefox); it turned out that while the conversion itself worked, FF did not provide the necessary functionality any more...

It's good to see that QuoteCollapse will survive the switch to webextensions. A few questions:

- I see references to toggleQuotes. Is this intentional to work together with toggleQuotes (or that folded in)?
- This reminds me of @stanio's PR for exposing functions for key bindings. Should we do both?
- License: Is this meant to be included in QuoteCollapse under the same (MPL) license, listing you as contributor (lijke stanio)? How should I spell out your name?

I'll see if there's something to clean up before and apply your changes after a bit more of testing.

**Comment by dillenger** [comment]
On 7/11/19 2:49 PM, Michael J Gruber wrote:
> Thanks for your efforts and for the ping!
> For another extension of mine, I had tried the conversion to a webextension (for Firefox); it turned out that while the conversion itself worked, FF did not provide the necessary functionality any more...
>
> It's good to see that QuoteCollapse will survive the switch to webextensions. A few questions:
>
> - I see references to toggleQuotes. Is this intentional to work together with toggleQuotes (or that folded in)?
toggleQuotes is an extension by me, its functions are now included in this extension.
Just copying them without too much renaming was the easiest way to do that.
> - This reminds me of @stanio's PR for exposing functions for key bindings. Should we do both?
I don't know, I only found out about @stanio's functions after I finished this.
I like the Q key, it works the same as the Q key works in Pan.
> - License: Is this meant to be included in QuoteCollapse under the same (MPL) license, listing you as contributor (lijke stanio)? How should I spell out your name?
Make it Dillinger, that's my username on AMO/ATN, on GitHub it is dillenger, Dillinger was not available.
>
> I'll see if there's something to clean up before and apply your changes after a bit more of testing.
>
I already did some cleaning up, unpack chrome.jar, remove contents.rdf etc.
There probably are some SeaMonkey bits left in.

**Comment by dillenger** [comment]
Thunderbird 68 will be out very soon now, how about releasing it?

**Comment by mjg** [comment]
Thanks for the reminder and sorry for the delay.

I prefer doing changes one by one, so I did a "pure" webextension conversion (basically @dillenger 's conversion without the qcToggle additions). The plan is to release that as 2.0 so that in case of bug/change reports we know the reason is the conversion.

The plan is also to fold in @stanio 's and @dillenger 's additions on top of 2.0 in a later release. Do you think parallel updates to the 1.x branch (for TB 60) are worthwhile?

I'll atach a test xpi here before releasing, so feel free to report here:
[quotecollapse-2.0rc.zip](https://github.com/mjg/QuoteCollapse/files/3549869/quotecollapse-2.0rc.zip)

NB: The new manifest files allow only one author and no contributor any more, I have to see how I can give you guys proper credit.

**Comment by dillenger** [comment]
It works, just a few remarks:

You reverted to the old pre-TB60 styles, these don't look too good on TB68.

As long as you keep the minimum version 68.0 it is no problem to upload it to ATN.
Ignore the warning, TB60 users will only see the old version until they upgrade, and when they do upgrade the add-on will also be upgraded automatically.

For some of my other add-ons I've used an about dialog for credits etc.
It is accessed through the legacy key in manifest.json:

```  
  "legacy" : {
    "options" : {
      "page" : "chrome://phoenityButtons/content/aboutButtons.xul",
      "open_in_tab" : false
    }
  },
```

**Comment by mjg** [comment]
OK, 2.0 is up (fc26af9), attributions solved differently.

I'll close this one (thanks again) but keep the toggle button in mind for an extra update.
