### ISSUE TITLE
Support for Thunderbird 78

### ISSUE THREAD

**Issue by marxin** [mjg/QuoteCollapse#14]
The Add-On is loaded in the version but does not work.
Thanks.

**Comment by mjg** [comment]
Just to confirm: Ist this with QC 2.0? Do you see twisties at all, or some collapsed quotes? Or is there no visual impact by QC at all?

I'm a bit behind on pull requests and very behind on FF&TB development but I try to keep my AddOns alive for the users as long as technically possible. Sometimes, such as for FF/LocalLink, it is made impossible by Mozilla's new extension platform.

**Comment by marxin** [comment]
> Just to confirm: Ist this with QC 2.0?

Yes.

> Do you see twisties at all, or some collapsed quotes? Or is there no visual impact by QC at all?

There's no visual impact.

> 
> I'm a bit behind on pull requests and very behind on FF&TB development but I try to keep my AddOns alive for the users as long as technically possible. Sometimes, such as for FF/LocalLink, it is made impossible by Mozilla's new extension platform.

Apparently Thunderbird is moving to the WebExtensions (same what Firefox supports) and you may need something what's mentioned here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1504475

Anyway, thanks for working on that.

**Comment by mjg** [comment]
Thanks for confirming.
QuoteCollapse is marked "incompatible" in the list of your AddOns, I guess.

QuoteCollapse 2.0 is a WebExtension already (this was required for the 60 series), but now they move again from WebExtensions to MailExtensions. We'll see if the new API suffices.

**Comment by mjg** [comment]
So, it seems that for TB 78, they want us to adjust to a new "experimental API" (because the proper API is so limted in fucntionality) while - at the same time - telling us that that will go away.

"Proper" MailExtensions are hampered by bugs like [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1504475) whose resolution should be in TB 82. Oh well.

**Comment by vsrawat** [comment]
Please update this useful addon to work with TB78+.

TB/FF are making lots of changes in quick succession, that is unsettling users also, developers too. Please stand with users and support us by making required modification even if it seems a wastage of time and efforts.

Your commitment is to your users and fans.

Thanks.

**Comment by mjg** [comment]
Thanks for the encouragement (and the postive feedback on the addon site).

The switch to TB78 must be frustrating on many levels. It affects even major functionality like PGP/GPG which will not come back in its original form (in terms of seemless key management between TB and GPG), it seems.

I'm still committed to adapting QC, even though I have basically switched away from TB. Last time I checked the new extension framework wasn't ready for that (missing functionality, sparse documentation) - and when I undertook the previous switch it turned out futile for the following one, but I will check again, hopefully over the holidays.

**Comment by marxin** [comment]
@mjg I must also say that the plug-in saves my day.
I can't see how people can live without collapsing of quotes.
In the case of a mailing list (like GCC), we use quoting for replies to patches.

**Comment by drscriptt** [comment]
+1 / Me Too

I have been using and loving QuoteCollapse for years.  I badly miss it in TB 78.

I look forward to seeing what the future is for QC in TB 83 (pursuant to comment above).

**Comment by vsrawat** [comment]
Actually, I have reverted to tb 60.9.1 solely because after that they 
have put "profile lock", a different profile for each version. This was 
somehow giving problem with my backup with freefilesync I don't know 
why. each Time I ran this backup utility, all my ff and tb settings were 
gone and it had to sync from back up from site, download many mbs of 
data, and all extensions, several were not even downloaded, all addon 
settings are not at all saveable or downloadable.

It was an utter mess.

So I have reverted to tb 60.9.1 and ff 66.0.5 that were last versions 
before that stupid profile lock, one profile for each version feature.

I am not updating tb and ff.

And thus, quote collapse is working again in my version.

Thanks.
-- 
Rawat

**Comment by julianlzb87** [comment]
I get around the QC problem not working on later TB releases by preventing TB updating beyond 68.10.
I refuse the updates when prompted and have saved the TB 68.10 installation file in case I update by mistake.

As as non developing user I value QC above anything I've heard about in later versions of TB. 

My laptop is well maintained with respect to security so I'm prepared to take the risk of TB 68.10
perhaps not being the latest word in security in order that I keep QC great usability improvements. 

If I'm taking risks I don't understand I'd appreciate being corrected. 

Cheers.

**Comment by vsrawat** [comment]
Same here. I am sticking to TB60.1, because, later on, ff has introduced 
version based different profile, that creates problem while backing up 
the profile using software, I couldn't figure out what is happening. 
After I take backup, starting ff shows it as reset and it syncs all 
things from ff-cloud and all my changes and customisations of extensions
are gone. so I got fed up with version-wise profiles, and "down"-dated 
to last versions of tb-ff before version-wise profiles.

--
Any way, I want to share with Julian this method, taken from the net. 
Julian is cancelling updating tb everytime, and might inadvertently 
click Yes some time and will have to downgrade again manually.

The following method permanently removes tb/ ff update prompting.

locate the sub-folder where your "thunderbird.exe" (or "firefox.exe") 
file is,
create a sub-folder called "distribution" next to the EXE file,
create a file "policies.json" inside the "distribution\" sub-folder. Put 
the following content in this json file. (Plain Text)

     to disable/stop application update completely, use below policy rule:

     {
       "policies": {
           "DisableAppUpdate": true
       }
     }

That's it. do it all with ff-tb closed.

You can search on the net to see the authenticity of it and try that.

Thanks.
-- 
Rawat

**Comment by paai** [comment]
If I nag about thunderbird it is not because I am ungrateful for the twenty-odd years that they provided an excellent and free email/usenet client.
But I really need Quote Collapse and it is sad that the developers choose to break it  and keep breaking it in favour of some esoterical improvements. I gladly went back to version 68 and will stay there.
Just my two Eurocents.

Paai

**Comment by marxin** [comment]
Just a comment for all people who have been still suffering with a recent Thunderbird release.
There's an alternative Add-On: https://addons.thunderbird.net/en-US/thunderbird/addon/quotecolors/

**Comment by mjg** [comment]
> Just a comment for all people who have been still suffering with a recent Thunderbird release.
> There's an alternative Add-On: https://addons.thunderbird.net/en-US/thunderbird/addon/quotecolors/

That is great news! I was always hoping that a similar Add-On would be ported - back then I had learned some stuff from the old QuoteColors already. Apparantly, the new QuoteColors even incorporated QuoteCollapse's JavaScript code (with proper attribution, all good here). I encourage you try it out and report back here so that I can deprecate QuoteCollapse with the appropriate pointers to the new collapsing QuoteColors.

**Comment by jicama** [comment]
Note that it seems QuoteColors only does collapsing for Thunderbird 91, not 78.

**Comment by marxin** [comment]
> That is great news! I was always hoping that a similar Add-On would be ported - back then I had learned some stuff from the old QuoteColors already. Apparantly, the new QuoteColors even incorporated QuoteCollapse's JavaScript code (with proper attribution, all good here).

Exactly, I was also positively surprised!

>  I encourage you try it out and report back here so that I can deprecate QuoteCollapse with the appropriate pointers to the new collapsing QuoteColors.

The first impression is very positive, the idea of using background-color works for me. What I miss is hotkey support:
https://gitlab.com/ThunderbirdMailDE/quote-colors/-/issues/4

I would definitely recommend promoting the new add-on.

**Comment by marxin** [comment]
> Note that it seems QuoteColors only does collapsing for Thunderbird 91, not 78.

Yep! Heh, have you been using TB for the GCC development as well?

**Comment by mjg** [comment]
So, while technically this issue remains unresolved, it is fixed for TB 91+ now. So I close it after pointing to QCC.

**Comment by marxin** [comment]
Thanks! I would recommend making this repository `readonly` now.
