### ISSUE TITLE
Collapsed quote cannot be expanded on certain circumstanceas 

### ISSUE THREAD

**Issue by svitalsky** [mjg/QuoteCollapse#4]
Thunderbrd 52.7.0 on Ubuntu 16.04, QuoteCollapse 1.0, using customisation from the [official page](http://mjg.github.io/QuoteCollapse/customising.html) to have all quotes expanded by default (first example on the page, used as is, without any editing). Without the customization the bellow problem does not occur.

When:
- a message contains nested quotes and
- I let collapse the inner one, it's parent quote also collapses*), but if then
- I expand the parent one again and
- I want to expand the child,

it does **NOT** expand and makes the parent collapse back instead.

*Note: Apparently this works as intended in the code, although I am not particularly excited about this feature either.

The problem is probably at the lines 90–91 of quotecollapse.js (I do not understand the logic there, i.e. why only the `false` value of qctoggled may be returned and `true` should be ignored, but I didn't really analyse it). When I simplify it like this it works OK for me.

```patch
90,91c90,91
<       if(current.nodeName == "BLOCKQUOTE" && current.getAttribute("qctoggled") != "true")
<         return false;
---
>       if(current.nodeName == "BLOCKQUOTE")
>         return current.getAttribute("qctoggled") == "true";
```

**Comment by mjg** [comment]
The issue here is the following: before 1.0, things were completely symmetric between toggled and not toggled, because the typical use was shown vs. not shown, and you couldn't possibly click on something that wasn't shown. Therefore, it didn't matter whether you had a configuration "false = shown" (default) or "false = hidden" (what you use).

With the changes in 1.0 that are aimed at partially showing instead of hiding quotes, it's possible to toggle something inside something that is "hidden" (partially shown), and expanding that should propagate up so that it's fully shown. But you wouldn't want to propagate "hidden" in the same way as you want to propagate "expanded", obviously.

So, these changes have "toggled means expanded" in mind, which does the wrong thing for your use case. I'm wondering whether we can and should make the propagation even smarter, or simply introduce an option "expand by default" (or "expand N levels by default", defaulting to 0) which makes QC set those "toggles" right away (so that "toggled" always means "expanded", and your use cases is supported by options).

**Comment by svitalsky** [comment]
@mjg Thx for the comment, I thought it would be something like that. As for the possible ways to go on I'd vote for options “expand by default” in the settings, and also—unrelated to this problem—for another option to have not-propagating collapse without Ctlr key by default (I've swapped the lines 178 and 180 for myself).

**Comment by stanio** [comment]
> I'm wondering whether we can and should make the propagation even smarter...

I guess I could tweak the `_getState` function to account for the computed value of the `max-height` property, or even compare element's [`scrollHeight`](https://developer.mozilla.org/docs/Web/API/Element/scrollHeight) to its [`clientHeight`](https://developer.mozilla.org/docs/Web/API/Element/clientHeight).  May be have that just in `_onClick` for computing the value of the `bubble` parameter to `_setState`.  I'll prepare a PR for it later today.
